debug: false

server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: spring-webflux-simple
  profiles:
    active: default
  lifecycle:
    timeout-per-shutdown-phase: "20s"
  datasource:
    url: jdbc:h2:mem:customerdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      platform: h2
